import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.ImageIcon;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * f3.java
 *
 * Created on Oct 10, 2013, 7:56:13 PM
 */

/**
 *
 * @author Admin
 */
public class sale extends javax.swing.JFrame {

    /** Creates new form f3 */
    public sale() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ntf = new javax.swing.JTextField();
        ebtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        mrptf = new javax.swing.JTextField();
        bbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        dtf = new javax.swing.JTextField();
        tchk = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        ptf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ddrb = new javax.swing.JRadioButton();
        crb = new javax.swing.JRadioButton();
        cdrb = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        atf = new javax.swing.JTextField();
        wctf = new javax.swing.JTextField();
        qtf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        wcbx = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SALES COUNTER-PURCHASE YOUR WEAPON AT VALID RATE");
        setIconImage(new ImageIcon("F:\\Project Pics\\dwdts.JPG").getImage());
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Armour number");

        jLabel2.setText("Name");

        jLabel4.setText("Ouantity");

        jLabel3.setText("Weapon Name");

        ntf.setEditable(false);
        ntf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntfActionPerformed(evt);
            }
        });

        ebtn.setText("Enter Transaction");
        ebtn.setEnabled(false);
        ebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebtnActionPerformed(evt);
            }
        });

        jLabel5.setText("MRP of Weapon");

        mrptf.setEditable(false);
        mrptf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrptfActionPerformed(evt);
            }
        });

        bbtn.setText("Back to Counter");
        bbtn.setEnabled(false);
        bbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Date");

        dtf.setEditable(false);
        dtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtfActionPerformed(evt);
            }
        });

        tchk.setText("YES, I HAVE READ THE TERMS AND CONDITION AND PURCHASE LICENSE AGREEMENT");
        tchk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tchkActionPerformed(evt);
            }
        });

        jLabel7.setText("Price");

        ptf.setEditable(false);
        ptf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptfActionPerformed(evt);
            }
        });

        jLabel8.setText("Weapon Code");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Mode of Payment"));

        buttonGroup1.add(ddrb);
        ddrb.setText("Demand Draft");

        buttonGroup1.add(crb);
        crb.setText("Cheaque");

        buttonGroup1.add(cdrb);
        cdrb.setText("Credit/Debit Card");
        cdrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdrbActionPerformed(evt);
            }
        });

        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cdrb)
                    .addComponent(ddrb)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(crb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cdrb)
                .addGap(11, 11, 11)
                .addComponent(ddrb)
                .addGap(10, 10, 10)
                .addComponent(crb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        atf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                k1(evt);
            }
        });

        wctf.setToolTipText("CODE MUST BE OF ONLY 5 WORDS");
        wctf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wctfActionPerformed(evt);
            }
        });
        wctf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                wctfFocusGained(evt);
            }
        });

        qtf.setEditable(false);
        qtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                k3(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Algerian", 3, 24));
        jLabel9.setText("PURCHASE YOUR WEAPON AT VALID RATE");

        wcbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT YOUR CHOICES", "=============", " ", "ON DEMAND GRANADES", "==============", "M67 FRAGMENTATION GRANADES", "AN/M14 THERMITE GRANADES", "AN/M8 WHITE SMOKE GRANADES", "AN/M18 COLOURED SMOKE GRANADES", "M100 GRANADE RIFLE ENTRY MUNITION(GREM)", " ", "HAND GUNS", "=======", "M1911A1", "M9 (BERETTA 92FS, 9*19MM)", "M11 (SIG Sauer P228, 9*19MM )", "MK 25 MOD 0 (SIG P226 MK25, 9*19MM)", "MEU  ( SOC) PISTOLS(.45 ACP)", "MARK 23 equipped with supresser and laser aiming module", "HK45C with an extended threaded barrel", "P11 UNDER WATER PISTOLS", " ", "RIFFLES", "========", "M16A4, (5056*45mm NATO)", "M14 SMUD", "M16A2", "M16A3", "SCAR-H MK 17 MOD 0", "XM29", "AR-15/COLT MODEL 601/602", "M870 MCS", " ", "CARBINES", "========", "M4 CABRINES", "GUU-5/P", "M231-FPW", "HK 416", "M2 CABRINES", "THOMPSON LIGHT RIFLE", " ", "ANTI-TANKS/ASSAULTS", "========", "M72/A1/A2/A3/A4 LAW ANTITANK ROCKET LAUNCHERS(66mm)", "M202 FLASH INCENDIARY ROCKET LAUNCHERS", "M203/A1/A2/ GRANADES LAUNCHERS", "FGM-148 JAVELIN", "AT4 MULTI USE CRUDE BLASTERS", " " }));
        wcbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wcbxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(ebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(bbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(atf, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wcbx, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtf)
                            .addComponent(wctf)
                            .addComponent(ntf)
                            .addComponent(dtf, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                            .addComponent(mrptf))))
                .addContainerGap(273, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(691, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(tchk)
                .addContainerGap(348, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(ptf, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(295, 295, 295))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(atf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ntf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(wcbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(wctf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(qtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mrptf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ptf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tchk)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebtnActionPerformed
int ans=JOptionPane.showConfirmDialog(null,"Do you want to save the data");
int qty, price ;
String date, armno, name, wcode ;
date=dtf.getText();
armno=atf.getText();
name=ntf.getText();
wcode=wctf.getText();
qty=Integer.parseInt(qtf.getText());
price=Integer.parseInt(ptf.getText());
if(ans==JOptionPane.YES_OPTION)
{
    try{
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost/dwdts","root","kvalwar");
    Statement stmt=con.createStatement() ;

String Query="INSERT INTO SALES VALUES ('"+armno+"', '"+name+"', "+"'"+date+"', "+"'"+wcode+"', "+qty+", "+price+" );";
   stmt.executeUpdate(Query);
JOptionPane.showMessageDialog(null,"REGISTRATING YOUR REQUEST");
JOptionPane.showMessageDialog(null,"SENDING TO SERVER");
this.setVisible(false);
new payment().setVisible(true);
// Ending of transaction with database
    }
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,"Sorry");
}
}

}//GEN-LAST:event_ebtnActionPerformed

    private void bbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtnActionPerformed
 this.setVisible(false) ;
                  new Manuplation_counter().setVisible(true);
}//GEN-LAST:event_bbtnActionPerformed

    private void dtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtfActionPerformed

    }//GEN-LAST:event_dtfActionPerformed

    private void ntfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ntfActionPerformed

    private void mrptfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrptfActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_mrptfActionPerformed

    private void tchkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tchkActionPerformed
if(tchk.isSelected()==true)
{
    ebtn.setEnabled(true);
}
else
{
    ebtn.setEnabled(false) ;
}
}//GEN-LAST:event_tchkActionPerformed

    private void ptfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptfActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ptfActionPerformed

    private void k1(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_k1
 try {
               Class.forName("java.sql.Driver");

    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/dwdts","root","kvalwar");
    Statement stmt=con.createStatement() ;
    String Query="SELECT * FROM ANOCHK WHERE ACODE='"+atf.getText()+"';";
    ResultSet rss=stmt.executeQuery(Query);
    while(rss.next())
    {
       String name ;
       name=rss.getString("name");
       ntf.setText(""+name);
    }

    }
catch(Exception e)
{

}
    }//GEN-LAST:event_k1

    private void wctfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wctfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wctfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(cdrb.isSelected()==true) {
            atf.setEnabled(true);
            wcbx.setEnabled(true);
           
            qtf.setEditable(true);
            bbtn.setEnabled(true);
        }else
            if(ddrb.isSelected()==true) {
                atf.setEnabled(true);
                wcbx.setEnabled(true);
              
                qtf.setEditable(true);
                       bbtn.setEnabled(true);
            }else
                if(crb.isSelected()==true) {
                    atf.setEnabled(true);
                    wcbx.setEnabled(true);
                   
                    qtf.setEditable(true);
                           bbtn.setEnabled(true);
                }else {
            atf.setEnabled(false);
            wcbx.setEnabled(false);
           
            qtf.setEditable(false);
                   bbtn.setEnabled(false);
                }
}//GEN-LAST:event_jButton1ActionPerformed

    private void cdrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdrbActionPerformed

}//GEN-LAST:event_cdrbActionPerformed

    private void k3(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_k3
int n1, n2, n3 ;
n1=Integer.parseInt(qtf.getText());
n2=Integer.parseInt(mrptf.getText());
n3=n1*n2 ;
ptf.setText(""+n3);
    }//GEN-LAST:event_k3

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    try {
               Class.forName("java.sql.Driver");

    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/dwdts","root","kvalwar");
    Statement stmt=con.createStatement() ;

        String query="select curdate();";
    ResultSet rs=stmt.executeQuery(query) ;
    while(rs.next())
 {
String date ;
date=rs.getString("curdate()");
dtf.setText(""+date);
    }
    }
catch(Exception e)
{

}
    }//GEN-LAST:event_formComponentShown

    private void wcbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wcbxActionPerformed
Object str1 ;
str1= wcbx.getSelectedItem() ;
wctf.setText(""+str1);
try
{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/dwdts","root","kvalwar");
    Statement stmt=con.createStatement() ;
    String query="select * from price where name='"+str1+"';";
    ResultSet rs=stmt.executeQuery(query) ;
    while(rs.next())
 {
int price ;
price=rs.getInt("price");
mrptf.setText(""+price);
    }
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,"Error In connectivity");
}
JOptionPane.showMessageDialog(null,"WEAPON CODE MUST CONTAIN ONLY 5 CHARACTERS\n"+"AND IS RELEVANT TO WEAPON NAME");
    }//GEN-LAST:event_wcbxActionPerformed

    private void wctfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_wctfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_wctfFocusGained

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField atf;
    private javax.swing.JButton bbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cdrb;
    private javax.swing.JRadioButton crb;
    private javax.swing.JRadioButton ddrb;
    private javax.swing.JTextField dtf;
    private javax.swing.JButton ebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mrptf;
    private javax.swing.JTextField ntf;
    private javax.swing.JTextField ptf;
    private javax.swing.JTextField qtf;
    private javax.swing.JCheckBox tchk;
    private javax.swing.JComboBox wcbx;
    private javax.swing.JTextField wctf;
    // End of variables declaration//GEN-END:variables

}
