import javax.swing.ImageIcon;
import javax.swing.JOptionPane ;
import java.sql.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Stock_list.java
 *
 * Created on Nov 16, 2013, 9:31:21 PM
 */

/**
 *
 * @author Admin
 */
public class Stock_list extends javax.swing.JFrame {

    /** Creates new form Stock_list */
    public Stock_list() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        PLBL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        wlist = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        rtf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dta = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WEAPON STOCK LIST-Select A Weapon For Purchase");
        setIconImage(new ImageIcon("F:\\Project Pics\\dwdts.JPG").getImage());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24));
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("PRESENT STOCK LIST OF AVAILABLE WEAPONS IN SERVER");

        jButton2.setText("PURCHASE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("HOME");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        PLBL.setFont(new java.awt.Font("Bodoni MT Black", 1, 18));
        PLBL.setText("             SELECT A OPTION FROM LIST TO PREVIEW IMAGE");
        PLBL.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        wlist.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "SELECT YOUR CHOICES'", "=============", " ", "ON DEMAND GRANADES", "==============", "M67 FRAGMENTATION GRANADES", "AN/M14 THERMITE GRANADES", "AN/M8 WHITE SMOKE GRANADES", "AN/M18 COLOURED SMOKE GRANADES", "M100 GRANADE RIFLE ENTRY MUNITION(GREM)", " ", "HAND GUNS", "=======", "M1911A1", "M9 (BERETTA 92FS, 9*19MM)", "M11 (SIG Sauer P228, 9*19MM )", "MK 25 MOD 0 (SIG P226 MK25, 9*19MM)", "MEU  ( SOC) PISTOLS(.45 ACP)", "MARK 23 equipped with supresser and laser aiming module", "HK45C with an extended threaded barrel", "P11 UNDER WATER PISTOLS", " ", "RIFFLES", "========", "M16A4, (5056*45mm NATO)", "M14 SMUD", "M16A2", "M16A3", "SCAR-H MK 17 MOD 0", "XM29", "AR-15/COLT MODEL 601/602", "M870 MCS", " ", "CARBINES", "========", "M4 CABRINES", "GUU-5/P", "M231-FPW", "HK 416", "M2 CABRINES", "THOMPSON LIGHT RIFLE", " ", "ANTI-TANKS/ASSAULTS", "========", "M72/A1/A2/A3/A4 LAW ANTITANK ROCKET LAUNCHERS(66mm)", "M202 FLASH INCENDIARY ROCKET LAUNCHERS", "M203/A1/A2/ GRANADES LAUNCHERS", "FGM-148 JAVELIN", "AT4 MULTI USE CRUDE BLASTERS", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        wlist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                wlistValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(wlist);

        jLabel2.setText("SHOWING RESULTS FOR:");

        rtf.setEditable(false);

        dta.setColumns(20);
        dta.setEditable(false);
        dta.setRows(5);
        jScrollPane1.setViewportView(dta);

        jButton1.setText("DETAILS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rtf, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton3)
                                    .addComponent(jButton2)
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(rtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(PLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(209, 209, 209))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
JOptionPane.showMessageDialog(null,"Proceeding Please Wait");
this.setVisible(false) ;
new sale().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void wlistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_wlistValueChanged
String i ;
i=      (String) wlist.getSelectedValue();
rtf.setText(""+i);

if(i.compareTo("M67 FRAGMENTATION GRANADES")==0)
{
    PLBL.setText("");
    PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/grenade_m67_400.jpg")));

     PLBL.setText("");

          
            
           
}else
    if(i.compareTo("AN/M14 THERMITE GRANADES")==0)
    {
            PLBL.setText("");
    PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/thermite_grenade_by_crafter08-d33bs7q.jpg")));


     PLBL.setText("");

          
            
            }
    else
        if(i.compareTo("AN/M8 WHITE SMOKE GRANADES")==0)
        {
                     PLBL.setText("");
    PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/Capture23.JPG")));

     PLBL.setText("");

          
            
             }else
            if(i.compareTo("AN/M18 COLOURED SMOKE GRANADES")==0)
            {
                     PLBL.setText("");
    PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/pi_969.jpeg")));

     PLBL.setText("");

          
            
             }else
                if(i.compareTo("M100 GRANADE RIFLE ENTRY MUNITION(GREM)")==0)
                {
                    PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/M84_stun_grenade.gif")));

     PLBL.setText("");

          
            
             }else
                    if(i.compareTo("M1911A1")==0)
                    {
                                        PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/320px-M1911_A1_pistol.jpg")));

     PLBL.setText("");

          
            
             }else
                        if(i.compareTo("M9 (BERETTA 92FS, 9*19MM)")==0)
                        {
                                PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/Capturegun.JPG")));

     PLBL.setText("");

          
            
            }else
                            if(i.compareTo("MK 25 MOD 0 (SIG P226 MK25, 9*19MM)")==0)
                            {
                                PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/200px-Sig_Sauer_P226_Mk_25.jpeg")));


     PLBL.setText("");

          
            
            }else
                            if(i.compareTo("M11 (SIG Sauer P228, 9*19MM )")==0)
                            {
                                 PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/320px-SIG_Sauer_P226_neu.jpg")));

     PLBL.setText("");

          
            
             }else
                                if(i.compareTo("MEU  ( SOC) PISTOLS(.45 ACP)")==0)
                                {
                                      PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/Meusoc861.gif")));

     PLBL.setText("");

          
            
             }else
                                    if(i.compareTo("MARK 23 equipped with supresser and laser aiming module")==0)
                                    {
                                           PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/320px-Mark23SuppressedLeft.jpg")));

     PLBL.setText("");

          
            
             }else
                                        if(i.compareTo("HK45C with an extended threaded barrel")==0)
                                        {
                                            PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/320px-HK45C_Threaded_Barrel.jpg")));

     PLBL.setText("");

          
            
             }else
                                            if(i.compareTo("P11 UNDER WATER PISTOLS")==0)
                                            {    PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/Capture98.JPG")));

     PLBL.setText("");

          
            
             }
                                            else
                if(i.compareTo("M16A4, (5056*45mm NATO)")==0)
                                                {
 PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/M16a4lh6.jpg")));

     PLBL.setText("");

          
            
             }else
                                                    if(i.compareTo("M16A2")==0)
                                                    {
                       PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/M16a2-final.png")));

     PLBL.setText("");

          
            
             }else
                                                        if(i.compareTo("SCAR-H MK 17 MOD 0")==0)
                                                        {
                                                             PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/320px-FN_SCAR-H_(Standard).jpg")));

     PLBL.setText("");

          
            PLBL.setText("Offer Price  :"+ i+'\n');
            }else
                                                            if(i.compareTo("M870 MCS")==0)
                                                            {
       PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/M870mcs.jpg")));


     PLBL.setText("");

          
            
            }else
                                                            if(i.compareTo("M4 CABRINES")==0)
                                                            {
       PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/320px-PEO_M4_Carbine_RAS.jpg")));

     PLBL.setText("");

          
            
            }else
                                                                if(i.compareTo("GUU-5/P")==0)
                                                                {
       PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/GAU_and_GUU.jpg")));

     PLBL.setText("");

          
            
             }else
                                                                if(i.compareTo("M231-FPW")==0)
                                                                {
                                                                       PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/M231_FPW.jpg")));

     PLBL.setText("");

          
            
             }else
                                                                    if(i.compareTo("HK 416")==0)
                                                                    {
                                                                        PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/320px-HK416.jpg")));

     PLBL.setText("");

          
            
            }else
                                                                        if(i.compareTo("M2 CARBINES")==0)
                                                                        {
 PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/m2.jpg")));

     PLBL.setText("");

          
            
             }else
if(i.compareTo("THOMPSON LIGHT RIFLE")==0)
{
     PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/Mass_Driver_Carbine_mkII_by_IgnusDei.jpg")));

     PLBL.setText("");

          
            
            }else
    if(i.compareTo("M72/A1/A2/A3/A4 LAW ANTITANK ROCKET LAUNCHERS(66mm)")==0)
    {
             PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/USAF_M72_LAW.jpg")));


     PLBL.setText("");

          
            
             }else
        if(i.compareTo("M202 FLASH INCENDIARY ROCKET LAUNCHERS")==0)
        {
                         PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/48ce028065a85&filename=lmfgm172srawpredator_zzang1847_zzang1847.jpg")));

     PLBL.setText("");

          
            
            
        }else
            if(i.compareTo("M203/A1/A2/ GRANADES LAUNCHERS")==0)
            {
                         PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/M203_1.jpg")));

     PLBL.setText("");

          
            
             }else
if(i.compareTo("FGM-148 JAVELIN")==0)
{
                            PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/Javelin+missile.jpg")));

     PLBL.setText("");

          
            
            }else
    if(i.compareTo("AT4 MULTI USE CRUDE BLASTERS")==0)
    {
                                   PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/320px-AT4-johnson2004-02-03.jpg")));

     PLBL.setText("");

          
            
             }else
        if(i.compareTo("M16A3")==0)
        {
                                               PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/M16A3-with-m203-guns-15559728-600-196.jpg")));

     PLBL.setText("");

          
            
            }else
            if(i.compareTo("XM29")==0)
            {
                                                          PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/748_xm29oicw.jpg")));

     PLBL.setText("");

          
            
            }else
                if(i.compareTo("M14 SMUD")==0)
                {
                                                                             PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/301px-CSA-2006-10-17-093634.jpg")));

     PLBL.setText("");

          
            
             }else
                    if(i.compareTo("AR-15/COLT MODEL 601/602")==0)
                    {
                                                                                                     PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/AR-1.jpg")));

     PLBL.setText("");

          
            
            }else
                       if(i.compareTo("M2 CABRINES")==0)
                    {
                                                        PLBL.setText("");
                PLBL.setIcon(new ImageIcon(this.getClass().getResource("/img/m2.jpg")));


     PLBL.setText("");

          
            PLBL.setText("Offer Price  :"+'\n');
             }
                       else{
    JOptionPane.showMessageDialog(null,"SELECT VALID OPTION");
                       }

}//GEN-LAST:event_wlistValueChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.setVisible(false);
new Manuplation_counter().setVisible(true) ;// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String i ;
i=rtf.getText();
        try
{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/dwdts","root","kvalwar");
    Statement stmt=con.createStatement() ;
    String query="select * from PRICE WHERE NAME='"+i+"';";
    ResultSet rs=stmt.executeQuery(query) ;
    while(rs.next())
 {
String price ;
price=rs.getString("price");
dta.setText("");
dta.append("Weapon Available at Full Quantity=10000"+'\n');
dta.append("------------------"+'\n');
dta.append("MRP OF WEAPON="+price+'\n');
dta.append("Thank You");

    }
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,"error");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock_list().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PLBL;
    private javax.swing.JTextArea dta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField rtf;
    private javax.swing.JList wlist;
    // End of variables declaration//GEN-END:variables

}
